name: 'test_post'
on:
  workflow_run:
    workflows: ["build-test"]
    types:
      - requested
      - completed

jobs:
  post-test-success:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - uses: actions/checkout@v2
      - run: exit 0

  post-test-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - uses: actions/checkout@v2
      - run: exit 1

  post-test-continue-on-error:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
      - uses: actions/checkout@v2
      - run: exit 1
        continue-on-error: true
      - run: exit 0
